version: 2

sources:
  - name: datalake
    description: "Raw Airbnb data from GCS"
    database: "{{ env_var('TF_VAR_project_id') }}"
    schema: "raw"
    loader: gcs

    tables:
      - name: listings
        external:
          location: "gs://{{ env_var('TF_VAR_gcs_bucket_name') }}/raw/Listings.csv"
          options:
            format: 'CSV'
            skip_leading_rows: 1
            allow_quoted_newlines: true
        columns:
          - name: listing_id
            data_type: STRING
            tests:
              - not_null
              - unique
          - name: name
            data_type: STRING
          - name: host_id
            data_type: STRING
          - name: host_since
            data_type: STRING
          - name: host_location
            data_type: STRING
          - name: host_response_time
            data_type: STRING
          - name: host_response_rate
            data_type: STRING
          - name: host_acceptance_rate
            data_type: STRING
          - name: host_is_superhost
            data_type: STRING
          - name: host_total_listings_count
            data_type: STRING
          - name: host_has_profile_pic
            data_type: STRING
          - name: host_identity_verified
            data_type: STRING
          - name: neighbourhood
            data_type: STRING
          - name: district
            data_type: STRING
          - name: city
            data_type: STRING
          - name: latitude
            data_type: STRING
          - name: longitude
            data_type: STRING
          - name: property_type
            data_type: STRING
          - name: room_type
            data_type: STRING
          - name: accommodates
            data_type: STRING
          - name: bedrooms
            data_type: STRING
          - name: amenities
            data_type: STRING
          - name: price
            data_type: STRING
          - name: minimum_nights
            data_type: STRING
          - name: maximum_nights
            data_type: STRING
          - name: review_scores_rating
            data_type: STRING
          - name: review_scores_accuracy
            data_type: STRING
          - name: review_scores_cleanliness
            data_type: STRING
          - name: review_scores_checkin
            data_type: STRING
          - name: review_scores_communication
            data_type: STRING
          - name: review_scores_location
            data_type: STRING
          - name: review_scores_value
            data_type: STRING
          - name: instant_bookable
            data_type: STRING
      - name: reviews
        external:
          location: "gs://{{ env_var('TF_VAR_gcs_bucket_name') }}/raw/Reviews.csv"
          options:
            format: 'CSV'
            skip_leading_rows: 1
            allow_quoted_newlines: true
        columns:
          - name: listing_id
            data_type: STRING
            tests:
              - not_null
          - name: review_id
            tests:
                - not_null
            data_type: STRING
          - name: date
            data_type: STRING
          - name: reviewer_id
            data_type: STRING
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns: ["listing_id", "review_id"]

